### ISSUE TITLE
Add optional ignore parameter to getDiff

### ISSUE THREAD

**Issue by VictorAssis** [cosmicanant/recursive-diff#11]
Hi, im using this library to get the diff when a record changes and then register the log with the differences.

Maybe could be helpful add a ignore parameter to set fields that we don't want to be analyzed. In my case, i don't want to diff the field updatedAt, so i need to remove this field before call getDiff.

**Comment by cosmicanant** [comment]
hey, why don't you consider a wrapper function on `getDiff` and use that to clear the diff items having `updatedAt` in their path? I would have wanted to let the `getDiff` work as a standard diff computation algorithm rather than supporting all the edge cases. In any case, we can always write a wrapper function to handle an edge case.
